### ISSUE TITLE
[FEATURE] Implement file sync

### ISSUE THREAD

**Issue by KorewaLidesu** [photosync/android-photosync-s3#1]
Is sync photo is only available feature for now?
Will file sync become feature soon?

**Comment by KorewaLidesu** [comment]
Can you implement Open/close for image folder?
Scroll thousand of pictures cause me pain ;;;;;

**Comment by tomekit** [comment]
Hi @KorewaLidesu,

Thanks for your input. There are multiple phases. Initially we will support more file types beyond the media. In later stage we will support two-way sync in a similar way as e.g. Dropbox.
It's hard for us to give exact ETA at this stage. 

Are more you interested in supporting more file types or two way sync?

**Comment by tomekit** [comment]
Hi @KorewaLidesu,

Open/Close feature for image folder has been implemented in the newest version of the app:
https://play.google.com/store/apps/details?id=com.photosync.s3

**Comment by tomekit** [comment]
Moved out remaining scope to different issues.
