### ISSUE TITLE
[FEATURE] Support media folders which are not recognized as media folders by Android

### ISSUE THREAD

**Issue by navehay** [photosync/android-photosync-s3#10]
Gallery only shows video in:
/storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Video/

But **not** in:
/storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Video/Sent/

And **not** in:
/storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Video/Private/

**Comment by tomekit** [comment]
Thanks for reporting this. I've investigated this issue. It seems that files in Whatsapp's Sent and Private folders are not recognized by the Android as `MEDIA_TYPE_VIDEO`, but instead it is recognized as: `MEDIA_TYPE_NONE` which we currently don't support as it would clutter the app with lots of non-media folders.
In future releases on top of standard media files we plan supporting different file formats.
There is a chance that  our team we'll find a workaround for this. Stay tuned.

**Comment by navehay** [comment]
I have a simple solution for you: Give the user option to add custom
folder(s) himself...

‫בתאריך יום א׳, 21 באוג׳ 2022 ב-17:50 מאת ‪Tomasz Raganowicz‬‏ <‪
***@***.***‬‏>:‬

**Comment by tomekit** [comment]
You're right, it's just we're not there yet.

**Comment by tomekit** [comment]
Moved here: https://syncaware.canny.io/feature-requests/p/support-for-different-file-formats-pdf-raw-live-photos-audio-any
