### ISSUE TITLE
need preview media function

### ISSUE THREAD

**Issue by mix9311** [photosync/android-photosync-s3#26]
I need to preview my media files on s3drive bucket,  such as mp3 audio ( mp4 video) files to play directly and no need to download it and play it from local. whatever android, web, windows client, hope to accomplish and finish it.
Going one step further, how to access google drive and onedrive 365 would be fine, thank u !

**Comment by tomekit** [comment]
Thanks for your feedback. In a next release in a couple days we will be supporting audio files in our Windows client.
We'll also add support for more audio formats.

Videos shall open already on Windows.
Audio and video shall open already on Android just fine.
Do you experience any problem with that?

Web support for media will be added soon, I've added roadmap item to specifically track this: https://s3drive.canny.io/feature-requests/p/support-for-audiovideo-preview-on-web

**Comment by tomekit** [comment]
Hi @mix9311,

We've just released media preview on Web (https://web.s3drive.app/).

I hope it all works well on your end.

Windows support for audio files will be deployed in a next few days.

Thanks !
