### ISSUE TITLE
Multiple Accounts Save as Label

### ISSUE THREAD

**Issue by mix9311** [photosync/android-photosync-s3#27]
Just like cyberduck, Multiple Accounts, Save them as Labels, and connect easily. support many different account all the time.
![Uploading image.png…]()
![Uploading 屏幕截图 2023-05-01 201745.png…]()

**Comment by tomekit** [comment]
Thank you for your feedback. Do I understand correctly that you would like to specify custom label / name for each of the account?
I've created the roadmap item for that one: https://s3drive.canny.io/feature-requests/p/allow-to-create-custom-name-for-profile
