### ISSUE TITLE
bunnycdn storage

### ISSUE THREAD

**Issue by mix9311** [photosync/android-photosync-s3#28]
I didn't find bunny.net 's bucket endpoint and two access keys, input "sg.storage.bunnycdn.com" seems to be wrong, 
they told me this--- Connected Pull Zones:
Use these settings when connecting to your storage zone to manage your files. We recommend a client such as [FileZilla](https://filezilla-project.org/). To learn how to use the storage API, you can have a look at our [storage API documentation](https://docs.bunny.net/reference/storage-api).

Username
   &  Hostname(almost == endpoint)

   &  Connection type

   &   Port   & Password   &  Read-only password  & API
    The final API means This is the key you can use to programmatically update your zones or account settings via the [bunny.net API] (https://docs.bunny.net/reference/bunnynet-api-overview). Make sure to keep it safe.

**Comment by tomekit** [comment]
Quick research that I've did just now is that Bunny doesn't seem to support S3 protocol which is a requirement.
Attached storage API doc: https://docs.bunny.net/reference/storage-api seem to be different than S3 protocol, there is no mention of S3 anywhere.

**Comment by tomekit** [comment]
We'll be looking on supporting more protocols / clouds, but our main goal is to complete integration with S3 first.
Roadmap item: https://s3drive.canny.io/feature-requests/p/add-support-for-google-drive-and-onedrive

If you want to connect from S3Drive to non-S3 endpoint then you'll need to find a project, e.g.: https://github.com/gaul/s3proxy or similar and use it together with S3Drive.

I've found an article which might be helpful for you. You can set up Bunny CDN in front of S3, check instructions for Backblaze: https://support.bunny.net/hc/en-us/articles/360018649972-How-to-speed-up-your-Backblaze-B2-file-delivery-with-Bunny-CDN but it's not something we tried ourselves.
