### ISSUE TITLE
Web Client doesnt work for Storj S3

### ISSUE THREAD

**Issue by navehay** [photosync/android-photosync-s3#4]
I get this message (attached). See on bottom.
![Screenshot_20220817-030131](https://user-images.githubusercontent.com/574480/185005466-100cf3a9-d3e4-43ff-b4f0-9723619b91ce.png)

**Comment by tomekit** [comment]
Thanks for reporting. Fix (https://github.com/photosync/websyncaware.github.io/commit/44a057d223dea61e83513b71f8fa9864e6b7fba9) is now deployed.

Can you please confirm?

**Comment by navehay** [comment]
Yes thanks. But thumbnails are shown only for pics not for videos. See
attached screenshot

בתאריך יום ו׳, 19 באוג׳ 2022, 11:59, מאת Tomasz Raganowicz ‏<
***@***.***>:
